[package]
name = "sql_test"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
api = { path = "../api" }
catalog = { path = "../catalog" }
exec = { path = "../exec" }
sql = { path = "../sql" }

[dev-dependencies]
cargo-husky.workspace = true
